// Code generated by ginctl. DO NOT EDIT.
package types

// ChatItemInfo defines model for ChatItemInfo.
type ChatItemInfo struct {
	// Name 会话名称
	Name string `binding:"required" json:"name"`

	// Type 会话类型
	Type int `binding:"required,oneof=1 2" json:"type"`

	// Uid 会话id
	Uid uint64 `binding:"required" json:"uid"`
}

// CodeMessage defines model for CodeMessage.
type CodeMessage struct {
	// Code 状态码
	Code int `binding:"required" json:"code"`

	// Msg 状态信息
	Msg string `binding:"required" json:"msg"`
}

// MessageItemInfo defines model for MessageItemInfo.
type MessageItemInfo struct {
	// Content 消息内容
	Content string `binding:"required" json:"content"`

	// Nickname 发送者昵称
	Nickname string `binding:"required" json:"nickname"`

	// SendAt 发送时间
	SendAt int64 `binding:"required" json:"send_at"`

	// Type 消息类型
	Type int `binding:"required,oneof=1 2" json:"type"`

	// Uid 发送者id
	Uid uint64 `binding:"required" json:"uid"`
}
