// Code generated by ginctl. DO NOT EDIT.
package types

// CodeMessage defines model for CodeMessage.
type CodeMessage struct {
	// Code 状态码
	Code int `binding:"required" json:"code"`

	// Msg 状态信息
	Msg string `binding:"required" json:"msg"`
}
