// Code generated by goctl. DO NOT EDIT.
package home

import (
	baseHandler "github.com/hubogle/chatcode-server/internal/handler"
	handler "github.com/hubogle/chatcode-server/internal/handler/home"
	logic "github.com/hubogle/chatcode-server/internal/logic/home"
	"github.com/hubogle/chatcode-server/internal/repository"
	"github.com/hubogle/chatcode-server/internal/svc"

	"github.com/gin-gonic/gin"
)

func RegisterHomeRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	homeRepo := repository.NewHomeRepo(svcCtx)
	homeLogic := logic.NewHomeLogic(svcCtx, homeRepo)
	baseHandler := baseHandler.NewHandler(svcCtx)
	homeHandler := handler.NewHomeHandler(svcCtx, baseHandler, homeLogic)

	e.GET("/api/v1/home", homeHandler.HomeHandler)
}
