// Code generated by goctl. DO NOT EDIT.
package friend

import (
	baseHandler "github.com/hubogle/chatcode-server/internal/handler"
	handler "github.com/hubogle/chatcode-server/internal/handler/friend"
	logic "github.com/hubogle/chatcode-server/internal/logic/friend"
	"github.com/hubogle/chatcode-server/internal/middleware"
	"github.com/hubogle/chatcode-server/internal/repository"
	"github.com/hubogle/chatcode-server/internal/svc"

	"github.com/gin-gonic/gin"
)

func RegisterFriendRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	friendRepo := repository.NewFriendRepo(svcCtx)
	friendLogic := logic.NewFriendLogic(svcCtx, friendRepo)
	baseHandler := baseHandler.NewHandler(svcCtx)
	friendHandler := handler.NewFriendHandler(svcCtx, baseHandler, friendLogic)

	e.POST("/api/v1/friend/add", middleware.Auth, friendHandler.AddFriendHandler)
}
