// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatRoom = "chat_rooms"

// ChatRoom mapped from table <chat_rooms>
type ChatRoom struct {
	ID            uint32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string  `gorm:"column:name;not null" json:"name"`                       // 聊天室名称
	Password      *string `gorm:"column:password" json:"password"`                        // 聊天室密码
	Salt          *string `gorm:"column:salt" json:"salt"`                                // 密码盐，消息加密
	CreatedUserID int32   `gorm:"column:created_user_id;not null" json:"created_user_id"` // 创建者ID
	CreatedAt     int64   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     int64   `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt     *int64  `gorm:"column:deleted_at" json:"deleted_at"`
}

// IsEmpty determines whether the structure is empty
func (m *ChatRoom) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// GetID get the ID of the database table
func (m *ChatRoom) GetID() int64 {
	return int64(m.ID)
}

// TableName ChatRoom's table name
func (*ChatRoom) TableName() string {
	return TableNameChatRoom
}
