// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
