// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessageBasic = "message_basic"

// MessageBasic mapped from table <message_basic>
type MessageBasic struct {
	ID        uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserUID   uint32 `gorm:"column:user_uid;not null" json:"user_uid"` // 用户ID
	RoomUID   string `gorm:"column:room_uid;not null" json:"room_uid"` // 房间ID
	Content   string `gorm:"column:content;not null" json:"content"`   // 聊天内容
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *int64 `gorm:"column:deleted_at" json:"deleted_at"`
}

// IsEmpty determines whether the structure is empty
func (m *MessageBasic) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// GetID get the ID of the database table
func (m *MessageBasic) GetID() int64 {
	return int64(m.ID)
}

// TableName MessageBasic's table name
func (*MessageBasic) TableName() string {
	return TableNameMessageBasic
}
