// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePrivateMessage = "private_messages"

// PrivateMessage mapped from table <private_messages>
type PrivateMessage struct {
	ID         uint64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SenderID   int32  `gorm:"column:sender_id;not null" json:"sender_id"`     // 发送者ID
	ReceiverID int32  `gorm:"column:receiver_id;not null" json:"receiver_id"` // 接收者ID
	Content    string `gorm:"column:content;not null" json:"content"`         // 聊天内容
	CreatedAt  int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt  *int64 `gorm:"column:deleted_at" json:"deleted_at"`
}

// IsEmpty determines whether the structure is empty
func (m *PrivateMessage) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// GetID get the ID of the database table
func (m *PrivateMessage) GetID() int64 {
	return int64(m.ID)
}

// TableName PrivateMessage's table name
func (*PrivateMessage) TableName() string {
	return TableNamePrivateMessage
}
