// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRoom = "user_room"

// UserRoom mapped from table <user_room>
type UserRoom struct {
	ID        uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserUID   uint32 `gorm:"column:user_uid;not null" json:"user_uid"`   // 用户ID
	RoomUID   string `gorm:"column:room_uid;not null" json:"room_uid"`   // 房间ID
	RoomType  int32  `gorm:"column:room_type;not null" json:"room_type"` // 房间类型 1:群聊房间 2:私聊房间
	JoinedAt  int64  `gorm:"column:joined_at;not null" json:"joined_at"`
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *int64 `gorm:"column:deleted_at" json:"deleted_at"`
}

// IsEmpty determines whether the structure is empty
func (m *UserRoom) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// GetID get the ID of the database table
func (m *UserRoom) GetID() int64 {
	return int64(m.ID)
}

// TableName UserRoom's table name
func (*UserRoom) TableName() string {
	return TableNameUserRoom
}
