// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFriend = "user_friend"

// UserFriend mapped from table <user_friend>
type UserFriend struct {
	ID        uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    uint64 `gorm:"column:user_id;not null" json:"user_id"`     // 用户ID
	FriendID  uint64 `gorm:"column:friend_id;not null" json:"friend_id"` // 好友ID
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *int64 `gorm:"column:deleted_at" json:"deleted_at"`
}

// IsEmpty determines whether the structure is empty
func (m *UserFriend) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// GetID get the ID of the database table
func (m *UserFriend) GetID() int64 {
	return int64(m.ID)
}

// TableName UserFriend's table name
func (*UserFriend) TableName() string {
	return TableNameUserFriend
}
