app:
  version: v1.0.0
  addr: 0.0.0.0:8080
  env: debug

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: chatcode
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

log:
  level: debug
  format: json
  output: stdout
