// Code generated by ginctl. DO NOT EDIT.
package chat

// ChatPrivateReq defines parameters for ChatPrivate.
type ChatPrivateReq struct {
	// Content chat content
	Content string `binding:"required" json:"content"`

	// ToUserId to user id
	ToUserId int `binding:"required" json:"to_user_id"`
}

// ChatRoomReq defines parameters for ChatRoom.
type ChatRoomReq struct {
	// Content chat content
	Content string `binding:"required" json:"content"`

	// RoomId room id
	RoomId int `binding:"required" json:"room_id"`
}
