// Code generated by ginctl. DO NOT EDIT.
package room

import (
	"github.com/hubogle/chatcode-server/internal/types"
)

// GetRoomPersonResp 房间人员列表
type GetRoomPersonResp struct {
	List []types.ChatItemInfo `binding:"required" json:"list"`
}

// RoomCreateResp 创建房间
type RoomCreateResp struct {
	// RoomId 房间id
	RoomId uint64 `binding:"required" json:"room_id"`
}

// RoomCreateReq defines model for RoomCreateReq.
type RoomCreateReq struct {
	// Info 房间信息
	Info *string `json:"info,omitempty"`

	// Name 房间名称
	Name string `binding:"required" json:"name"`

	// Salt 房间密码
	Salt *string `json:"salt,omitempty"`
}

// RoomGetReq room get
type RoomGetReq struct {
	// Id room id
	Id int `binding:"required" uri:"id"`
}

// RoomPersonReq room person
type RoomPersonReq struct {
	// Id room id
	Id uint64 `binding:"required" uri:"id"`
}
