// Code generated by goctl. DO NOT EDIT.
package oauth

import (
	baseHandler "github.com/hubogle/chatcode-server/internal/handler"
	handler "github.com/hubogle/chatcode-server/internal/handler/oauth"
	logic "github.com/hubogle/chatcode-server/internal/logic/oauth"
	"github.com/hubogle/chatcode-server/internal/repository"
	"github.com/hubogle/chatcode-server/internal/svc"

	"github.com/gin-gonic/gin"
)

func RegisterOauthRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	oauthRepo := repository.NewOauthRepo(svcCtx)
	oauthLogic := logic.NewOauthLogic(svcCtx, oauthRepo)
	baseHandler := baseHandler.NewHandler(svcCtx)
	oauthHandler := handler.NewOauthHandler(svcCtx, baseHandler, oauthLogic)

	e.POST("/api/v1/login", oauthHandler.OauthLoginHandler)

	e.POST("/api/v1/logout", oauthHandler.OauthLogoutHandler)
}
