// Code generated by ginctl. DO NOT EDIT.
package user

// LoginResp 登录成功
type LoginResp struct {
	Token string `binding:"required" json:"token"`

	// Uid 用户id
	Uid uint64 `binding:"required" json:"uid"`
}

// LoginReq defines model for LoginReq.
type LoginReq struct {
	// Account 用户名
	Account string `binding:"required" json:"account"`

	// Password 密码
	Password string `binding:"required" json:"password"`
}
