// Code generated by goctl. DO NOT EDIT.
package ping

import (
	baseHandler "github.com/hubogle/chatcode-server/internal/handler"
	handler "github.com/hubogle/chatcode-server/internal/handler/ping"
	logic "github.com/hubogle/chatcode-server/internal/logic/ping"
	"github.com/hubogle/chatcode-server/internal/repository"
	"github.com/hubogle/chatcode-server/internal/svc"

	"github.com/gin-gonic/gin"
)

func RegisterPingRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	pingRepo := repository.NewPingRepo(svcCtx)
	pingLogic := logic.NewPingLogic(svcCtx, pingRepo)
	baseHandler := baseHandler.NewHandler(svcCtx)
	pingHandler := handler.NewPingHandler(svcCtx, baseHandler, pingLogic)

	e.GET("/ping", pingHandler.PingHandler)
}
