// Code generated by ginctl. DO NOT EDIT.
package oauth

// LoginReq defines model for LoginReq.
type LoginReq struct {
	// Account 用户名
	Account string `binding:"required" json:"account"`

	// Password 密码
	Password string `binding:"required" json:"password"`
}
