// Code generated by ginctl. DO NOT EDIT.
package oauth

// LoginReq defines model for LoginReq.
type LoginReq struct {
	// Password 密码
	Password string `binding:"required" json:"password"`

	// Username 用户名
	Username string `binding:"required" json:"username"`
}
