openapi: 3.0.3
info:
  title: "ChatCode"
  version: "1.0.0"

paths:
  /ping:
    get:
      tags: [ping]
      summary: ping
      description: ping
      operationId: Ping
      x-group: ping
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/login:
    post:
      tags: [oauth]
      summary: user login
      description: user login
      operationId: OauthLogin
      x-group: oauth
      requestBody:
        $ref: '#/components/requestBodies/LoginReq'
      responses:
        200:
          $ref: '#/components/responses/LoginResp'

  /api/v1/logout:
    post:
      tags: [oauth]
      summary: user logout
      description: user logout
      operationId: OauthLogout
      x-group: oauth
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/home:
    get:
      tags: [home]
      summary: home page
      description: home page
      operationId: Home
      x-group: home
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/room/{id}:
    get:
      tags: [room]
      summary: room get
      description: room get
      operationId: RoomGet
      x-group: room
      x-middleware: auth
      parameters:
        - name: id
          in: path
          description: room id
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/room/join:
    post:
      tags: [room]
      summary: join room
      description: join room
      operationId: RoomJoin
      x-group: room
      x-middleware: auth
      requestBody:
        $ref: '#/components/requestBodies/RoomJoinReq'
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/room/create:
    post:
      tags: [room]
      summary: create room
      description: create room
      operationId: RoomCreate
      x-group: room
      x-middleware: auth
      requestBody:
        $ref: '#/components/requestBodies/RoomCreateReq'
      responses:
        200:
          $ref: '#/components/responses/RoomCreateResp'

  /api/v1/ws:
    get:
      tags: [ws]
      summary: websocket
      description: websocket chat
      operationId: ws
      x-group: ws
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/chat/list:
    get:
      tags: [chat]
      summary: chat list
      description: chat list
      operationId: chatList
      x-group: chat
      x-middleware: auth
      parameters:
        - name: room_id
          in: query
          description: room id
          required: true
          schema:
            type: integer
            format: uint64
        - name: page
          in: query
          description: page
          required: true
          schema:
            type: integer
        - name: page_size
          in: query
          description: page size
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

components:
  requestBodies:
    LoginReq:
      description: login request body
      content:
        application/json:
          schema:
            type: object
            properties:
              account:
                type: string
                description: 用户名
              password:
                type: string
                description: 密码
            required:
            - account
            - password

    RoomJoinReq:
      description: join room request body
      content:
        application/json:
          schema:
            type: object
            properties:
              room_id:
                type: integer
                format: uint64
                description: 房间id
            required:
            - room_id

    RoomCreateReq:
      description: create room request body
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: 房间名称
              info:
                type: string
                description: 房间信息
              salt:
                type: string
                description: 房间密码
            required:
            - name

  responses:
    LoginResp:
      description: 登录成功
      content:
        application/json:
          schema:
            description: 登录成功
            x-level-one: data
            allOf:
              - $ref: '#/components/schemas/CodeMessage'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token

    ChatListResp:
      description: 聊天记录
      content:
        application/json:
          schema:
            description: 聊天记录
            x-level-one: data
            allOf:
              - $ref: '#/components/schemas/CodeMessage'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object
                          properties:
                            user_id:
                              type: integer
                              format: uint64
                              description: 用户id
                            user_account:
                              type: string
                              description: 用户账号
                            room_id:
                              type: integer
                              format: uint64
                              description: 房间id
                            content:
                              type: string
                              description: 聊天内容
                            created_at:
                              type: string
                              description: 创建时间
                    required:
                      - list

    RoomCreateResp:
      description: 创建房间
      content:
        application/json:
          schema:
            description: 创建房间
            x-level-one: data
            allOf:
              - $ref: '#/components/schemas/CodeMessage'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      room_id:
                        type: integer
                        format: uint64
                        description: 房间id
                    required:
                      - room_id

    SuccessResp:
      description: 请求成功
      content:
        application/json:
          x-ignore-schema: true
          schema:
            $ref: '#/components/schemas/CodeMessage'

  schemas:
    CodeMessage:
      type: object
      properties:
        code:
          type: integer
          description: 状态码
        msg:
           type: string
           description: 状态信息
      required:
        - code
        - msg
