openapi: 3.0.3
info:
  title: "ChatCode"
  version: "1.0.0"

paths:
  /ping:
    get:
      tags: [ping]
      summary: ping
      description: ping
      operationId: Ping
      x-group: ping
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/login:
    post:
      tags: [oauth]
      summary: user login
      description: user login
      operationId: OauthLogin
      x-group: oauth
      requestBody:
        $ref: '#/components/requestBodies/LoginReq'
      responses:
        200:
          $ref: '#/components/responses/LoginResp'

  /api/v1/logout:
    post:
      tags: [oauth]
      summary: user logout
      description: user logout
      operationId: OauthLogout
      x-group: oauth
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/home:
    get:
      tags: [home]
      summary: home page
      description: home page
      operationId: Home
      x-group: home
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/room/{id}:
    get:
      tags: [room]
      summary: room page
      description: room page
      operationId: Room
      x-group: room
      parameters:
        - name: id
          in: path
          description: room id
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/chat/room:
    post:
      tags: [chat]
      summary: room chat
      description: room chat
      operationId: chatRoom
      x-group: chat
      x-middleware: auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: integer
                  description: room id
                content:
                  type: string
                  description: chat content
              required:
                - room_id
                - content
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/chat/private:
    post:
      tags: [chat]
      summary: private chat
      description: private chat
      operationId: chatPrivate
      x-group: chat
      x-middleware: auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                to_user_id:
                  type: integer
                  description: to user id
                content:
                  type: string
                  description: chat content
              required:
                - to_user_id
                - content
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/ws:
    get:
      tags: [ws]
      summary: websocket
      description: websocket chat
      operationId: ws
      x-group: ws
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

  /api/v1/chat/list:
    get:
      tags: [chat]
      summary: chat list
      description: chat list
      operationId: chatList
      x-group: chat
      x-middleware: auth
      parameters:
        - name: room_uid
          in: query
          description: room uid
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: page
          required: true
          schema:
            type: integer
        - name: page_size
          in: query
          description: page size
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/SuccessResp'

components:
  requestBodies:
    LoginReq:
      description: login request body
      content:
        application/json:
          schema:
            type: object
            properties:
              account:
                type: string
                description: 用户名
              password:
                type: string
                description: 密码
            required:
            - account
            - password

  responses:
    LoginResp:
      description: 登录成功
      content:
        application/json:
          schema:
            description: 登录成功
            x-level-one: data
            allOf:
              - $ref: '#/components/schemas/CodeMessage'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token

    ChatListResp:
      description: 聊天记录
      content:
        application/json:
          schema:
            description: 聊天记录
            x-level-one: data
            allOf:
              - $ref: '#/components/schemas/CodeMessage'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: object
                          properties:
                            user_uid:
                              type: integer
                              description: 用户uid
                            user_account:
                              type: string
                              description: 用户账号
                            room_uid:
                              type: string
                              description: 房间uid
                            content:
                              type: string
                              description: 聊天内容
                            created_at:
                              type: string
                              description: 创建时间
                    required:
                      - list

    SuccessResp:
      description: 请求成功
      content:
        application/json:
          x-ignore-schema: true
          schema:
            $ref: '#/components/schemas/CodeMessage'

  schemas:
    CodeMessage:
      type: object
      properties:
        code:
          type: integer
          description: 状态码
        msg:
           type: string
           description: 状态信息
      required:
        - code
        - msg
